JNU-econovation/Whoz-in-BE

.gitignore
modules/domain/src/main/java/com/whoz_in/domain/device/application/ExampleGetHandler.java
modules/domain/src/main/java/com/whoz_in/domain/member/application/MemberGetHandler.java
modules/domain/src/main/java/com/whoz_in/domain/shared/annotation/DomainService.java
modules/domain/src/main/java/com/whoz_in/domain/shared/annotation/Handler.java
modules/domain/src/main/java/com/whoz_in/domain/shared/domain/utils/StubRequesterInfo.java

[FEAT] @Component를 대체할 어노테이션 추가

---

modules/api/src/main/java/com/whoz_in/api/query/device_info/application/DeviceInfoViewer.java
modules/api/src/main/java/com/whoz_in/api/shared/application/query/View.java
modules/api/src/main/java/com/whoz_in/api/shared/application/query/Viewer.java
modules/api/src/test/java/com/whoz_in/api/architecture/ViewerTest.java

[FEAT, TEST] Viewer와 Viewer 테스트 추가 - 32,33,34

---

modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/process/ContinuousProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/process/TransientProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/config/NetworkConfig.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/ManagedLogDAO.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/arp/ArpLogProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/arp/ArpLogWriter.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/mdns/MdnsLogProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/mdns/MdnsLogWriter.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/MonitorInfo.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/MonitorLogProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/MonitorLogWriter.java

Log process interface

---

modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/SystemValidator.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/NetworkInterface.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/process/ContinuousProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/process/TransientProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/config/NetworkConfig.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/arp/ArpLogProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/mdns/MdnsLogProcess.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/MonitorLogProcess.java
modules/infrastructure/log-writer/src/main/resources/network-local.json
modules/infrastructure/log-writer/src/main/resources/network-prod.json
modules/network-api/src/main/resources/application.yml

[FEAT] Check environment

---

modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/SystemValidator.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/TimeLogger.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/arp/ArpLogParser.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/ChannelHopper.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/ChannelHopperConfig.java
modules/network-api/src/main/resources/application.yml

[FEAT] Channel hopper

---

modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/SystemValidator.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/SystemValidatorConfig.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/ChannelHopper.java

[FEAT] Check regularly network interface

---

modules/infrastructure/log-writer/build.gradle
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/validation/BiValidator.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/validation/ValidationException.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/validation/ValidationResult.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/common/validation/Validator.java

라베파에 로그를 임시적으로 저장하기 때문에 마리아 db 의존성 추가함

[DEPEND] Log writer mariadb

---

modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/managed/mdns/MdnsLogWriter.java
modules/infrastructure/log-writer/src/main/java/com/whoz_in/log_writer/monitor/MonitorLogWriter.java

close #90 
시도한 방법
1. 기존엔 병렬 스트림으로 프로세스를 만들고 동시성 제어가 안되는 Map에 저장하고 있었음. 초기화는 서버 실행 시 한 번만 이루어지므로 동시성 Map을 쓰기보단 병렬 스트림을 제거한다.
바로 해결됨

Fix mdns process

---

modules/network-api/src/main/java/com/whoz_in/network_log/config/WebMvcConfig.java

[FEAT] Network api CORS 설정

---

modules/domain/src/main/java/com/whoz_in/domain/member/MemberRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/member/MemberEntityJpaRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/member/MemberJpaRepository.java

#127 
- MemberRepository 의 getByName 반환 타입을 List로 변경하였습니다.

[REFACTOR] MemberRepository getByName 동명이인 처리 추가

---

modules/main-api/src/main/java/com/whoz_in/main_api/shared/presentation/MainApiGlobalExceptionHandler.java

#130 
- GlobalExceptionHandler 정의

[FEAT] main api GlobalExceptionHandler 정의

---

modules/domain/src/main/java/com/whoz_in/domain/member/model/Position.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/MemberOAuth2Login.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/MemberOAuth2LoginHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/MemberOAuth2SignUp.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/application/MemberOAuth2SignUpHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/presentation/MemberController.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/presentation/MemberOAuthSignUpAdditionalInfo.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/member/presentation/PositionDeserializer.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/oauth2/LoginSuccessHandler.java
modules/network-api/src/main/java/com/whoz_in/network_api/common/process/TransientProcess.java
modules/network-api/src/main/java/com/whoz_in/network_api/monitor/ChannelHopper.java

소셜 회원가입 시 자동 로그인
소셜 회원가입 로직 수정

[FEAT] ]Auto login when signup by social

---

.github/workflows/chat-gpt-code-review.yml

[FIX] github action script 오타 수정

---

.github/workflows/chat-gpt-code-review.yml

[FIX] github repository 오타 수정

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/config/ApiQueryJpaConfig.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/ActiveDeviceEntity.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/ActiveDeviceJpaViewer.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/ActiveDeviceRepository.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/event/ActiveDeviceEventHandler.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/event/InActiveDeviceEventHandler.java
modules/infrastructure/api-query-jpa/src/main/resources/application-api-query-jpa.yml

close #150 
#150 
기존에 ActiveDeviceRepository 및 InMemoryActiveDeviceRepository 를 JPA로 변경합니다.

[REFACTOR] ActiveDevice JPA 적용

---

.github/workflows/chat-gpt-code-review.yml

[REFACTOR] 모델명 변경 및 max 토큰 값 설정

---

modules/main-api/src/main/java/com/whoz_in/main_api/query/device/presentation/DeviceQueryController.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/MemberQueryController.java

#119 #176 
- MemberQueryController 를 하나 둬서 URI 를 `/api/v1/members`로 변경하였습니다.
- 응답 Response에 사용되는 클래스의 이름은 변경해야 합니다.

[REFACTOR] 동방 현황 조회 API URI Member 기준으로 변경

---

modules/infrastructure/api-query-jpa/src/main/resources/application-api-query-jpa.yml
modules/infrastructure/domain-jpa/src/main/resources/application-domain-jpa-local.yml
modules/infrastructure/domain-jpa/src/main/resources/application-domain-jpa.yml
modules/main-api/src/main/resources/application-main-api.yml
modules/master-api/src/main/java/com/whoz_in/master_api/private_ip/MainApiHandlerPrivateIpWriter.java
modules/network-api/src/main/java/com/whoz_in/network_api/private_ip/HttpPrivateIpWriter.java
modules/network-api/src/main/java/com/whoz_in/network_api/private_ip/PrivateIpUpdater.java
modules/network-api/src/main/java/com/whoz_in/network_api/private_ip/PrivateIpWriter.java
modules/network-api/src/main/resources/application-network-api.yml

close #182 
일단 내부 아이피 주기적으로 업데이트하여 해결했습니다.
이외 모듈 별 환경변수 설정이 좀 변경됐습니다. 노션을 확인하세요

[FIX] #182

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/event/ActiveDeviceEventHandler.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/event/InActiveDeviceEventHandler.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/Member.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/ActiveDeviceListHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/ActiveDeviceResponse.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberInfo.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberName.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberViewer.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/ActiveDeviceFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/DeviceFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/SpringDeviceStatusManager.java

#187 
- ActiveDeviceResponse에 generation 필드 추가
- ActiveDevice , InActiveDevice 판별 로직에 JPA Repository 적용
- InMemory 저장공간 삭제

[REFACTOR] 동방 현황 기능 로직 수정

---

modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/MembersInRoomHandler.java

#187 
- 동방 현황 조회 API 응답에서, size 필드에 현재 Active 상태인 멤버의 수를 담도록 수정합니다.

[REFACTOR] Active Member의 수만 담도록 변경

---

modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/SpringDeviceStatusManager.java

[REFACTOR] ActiveDevice , InActiveDevice 판별 주기 수정

---

modules/domain/src/main/java/com/whoz_in/domain/device/event/DeviceInfoUpdated.java
modules/domain/src/main/java/com/whoz_in/domain/device/exception/DeviceInfoAlreadyRegisteredException.java
modules/domain/src/main/java/com/whoz_in/domain/device/exception/NoDeviceInfoException.java
modules/domain/src/main/java/com/whoz_in/domain/device/model/Device.java
modules/domain/src/main/java/com/whoz_in/domain/device/model/DeviceInfo.java
modules/domain/src/main/java/com/whoz_in/domain/network_log/ManagedLogRepository.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/Member.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/MemberJpaViewer.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/managed/ManagedLogEntityRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/managed/ManagedLogJpaRepository.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/device/application/DeviceInfoEdit.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/device/application/DeviceInfoEditHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/device/presentation/DeviceController.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/JwtAuthenticationFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityConfig.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityFilterChainConfig.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/UnknownEndpointFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberDetailInfo.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberDetailInfoGet.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberDetailInfoHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/application/MemberViewer.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/member/presentation/MemberQueryController.java

[FEAT] 기기 맥 수정 api / 내 정보 조회 api / 인증 관련 로직 수정 및 리팩토링

---

modules/domain/src/main/java/com/whoz_in/domain/device/DeviceRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/device/DeviceEntityRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/device/DeviceJpaRepository.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/ActiveDeviceFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/InActiveDeviceFilter.java

#200 
- findByMacs 메소드 추가
- findByDeviceIds 메소드 추가

[REFACTOR] 동방 현황 최신화 로직 중 SQL 로그 빈도 축소

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/DeviceJpaViewer.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/DeviceCount.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/MembersInRoomHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/exception/RegisteredDeviceCountException.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/view/DeviceViewer.java

close #203 
#203 
- 기기를 1개 이상 등록하지 않았을 경우 예외를 추가합니다.
- 동방 현황 API 조회시, 기기를 1개 이상 등록했는지 검증하는 로직을 추가합니다.
- 사용자가 등록한 기기의 개수를 보여주는 DeviceCount View 를 추가합니다.

[FEAT] 기기 1개 이상 미등록 예외 추가

---

modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/view/ActiveDevice.java

[FIX] connectedTime 이 null 일 경우 버그 수정2

---

modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/view/ActiveDevice.java

#208 
- true / false 반대로 입력 수정

[FIX] ActiveDevice isActive 메소드 로직 수정

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceEntity.java
modules/main-api/src/main/java/com/whoz_in/main_api/query/device/application/active/view/ActiveDevice.java

[FIX] ActiveDevice isActive 로직 수정

---

modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityFilterChainConfig.java

[REFACTOR] Main-API CORS 설정 수정

---

modules/domain/src/main/java/com/whoz_in/domain/network_log/ManagedLogRepository.java
modules/domain/src/main/java/com/whoz_in/domain/network_log/MonitorLogRepository.java
modules/domain/src/main/java/com/whoz_in/domain/network_log/NoManagedLogException.java
modules/domain/src/main/java/com/whoz_in/domain/network_log/NoMonitorLogException.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/ExceptionLoggingFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/RequestCachingFilter.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/presentation/ExceptionLogger.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/presentation/HttpRequestInfoExtractor.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/presentation/UnhandledExceptionHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/presentation/WhozinExceptionHandler.java

[REFACTOR] 예외 로깅

---

.github/workflows/main-api-deploy.yml
.github/workflows/network-api-deploy.yml

closes #227 
- main-api , netowkr-api 에 각각 배포 자동화를 수행하는 스크립트를 추가합니다.
- github secret 환경 변수를 설정합니다.

[FEAT] CD 스크립트 작성

---

modules/domain/src/main/java/com/whoz_in/domain/feedback/FeedbackRepository.java
modules/domain/src/main/java/com/whoz_in/domain/feedback/event/FeedbackCreated.java
modules/domain/src/main/java/com/whoz_in/domain/feedback/model/Feedback.java
modules/domain/src/main/java/com/whoz_in/domain/feedback/model/FeedbackId.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackConverter.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackEntity.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackEntityJpaRepository.java
modules/infrastructure/domain-jpa/src/main/java/com/whoz_in/domain_jpa/feedback/FeedbackJpaRepository.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/application/FeedbackSend.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/application/FeedbackSendHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/feedback/presentation/FeedbackController.java
modules/main-api/src/main/java/com/whoz_in/main_api/config/security/SecurityFilterChainConfig.java

close #217 
기능 구현은 했는데 머지하기 전까지 리팩토링해볼게요
베타 화이팅!

[FEAT] VOC 기능

---

.github/workflows/main-api-deploy.yml
.github/workflows/network-api-deploy.yml
modules/domain/src/main/java/com/whoz_in/domain/device/event/DeviceDeleted.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/ActiveDeviceRepository.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/device/active/event/ActiveDeviceDeletedEventHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/command/device/application/DeviceRemoveHandler.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/event/DeviceDeletedEvent.java
modules/main-api/src/main/java/com/whoz_in/main_api/shared/domain/device/active/event/DeviceDeletedEventHandler.java

#235 
- 기기 삭제 시, ActiveDeviceEntity 도 삭제합니다.
- github action script 수정
- 무조건 최신 코드를 가져올 수 있도록 수정

[FEAT] Active Device 삭제 기능

---

.github/workflows/deploy.yml
.github/workflows/network-api.yml

#252
- 커밋 메세지 개행 문자 제거
- yml 파일 인코딩 변경

[REFACTOR] GitHub Action workflow를 수정합니다.

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/main-api.yml
.github/workflows/network-api.yml

#254
- discord webhook url 환경 변수 추가
- CI 동작 이벤트 추가 (develop branch push event)

[REFACTOR] GitHub workflow 수정

---

.github/workflows/ci.yml

[REFACTOR] ci 트리거 이벤트 수정

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/DeviceConnectionService.java
modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/shared/service/MemberConnectionService.java

#272 
- 성능 오류로 인해, Propagation 종류를 Required 로 수정합니다.

[FIX] Transactional Propagation 종류를 수정합니다.

---

modules/infrastructure/api-query-jpa/src/main/java/com/whoz_in/api_query_jpa/member/activity/today/TodayActivity.java
modules/network-api/src/main/java/com/whoz_in/network_api/common/network_interface/NetworkInterfaceManager.java
modules/network-api/src/main/java/com/whoz_in/network_api/config/NetworkInterfaceAlertNotifier.java
modules/network-api/src/main/java/com/whoz_in/network_api/system/UsbReconnector.java

[FEAT] 네트워크 인터페이스 에러 알림 유예
